version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: valere-postgres-db
    ports:
      - "5432:5432"
    environment:
      DATABASE_HOST: localhost
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sport-club